P127_Pronia/P127_Pronia/Controllers/PlantController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using P127_Pronia.DAL;
using P127_Pronia.Models;
using P127_Pronia.ViewModels;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace P127_Pronia.Controllers
{
    public class PlantController:Controller
    {
        private readonly ApplicationDbContext _context;

        public PlantController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Detail(int? id)
        {
            if(id is null || id == 0)
            {
                return NotFound();
            }
            Plant plant = await _context.Plants.Include(p => p.PlantImages)
                .Include(p => p.PlantInformation).Include(p => p.PlantCategories).ThenInclude(p=>p.Category)
                .FirstOrDefaultAsync(p=>p.Id == id);

            List<Plant> plants = new List<Plant>();
            List<Plant> plantsRange = new List<Plant>();
            foreach (var item in plant.PlantCategories)
            {
                plants = _context.Plants.Where(x => x.PlantCategories.Any(z => z.CategoryId == item.CategoryId)).Include(x => x.PlantImages).ToList();

                plantsRange.AddRange(plants);
            }
           
            ViewBag.Plants = plantsRange.Distinct().ToList();

            if (plant is null) return NotFound();
            return View(plant);
        }

        public async Task<IActionResult> Partial()
        {
            List<Plant> plants = await _context.Plants.Include(p=>p.PlantImages).ToListAsync();

            return PartialView("_PlantsPartialView", plants);

        }

        public async Task<IActionResult> GetDetail(int id)
        {
            Plant plant =await _context.Plants.Include(x => x.PlantImages).Include(x=>x.PlantInformation).FirstOrDefaultAsync(x => x.Id == id);
            return PartialView("_detailplant",plant);
        }

        public async Task<IActionResult> AddBasket(int? id)
        {
            if (id is null || id == 0) return NotFound();

            Plant plant = await _context.Plants.FirstOrDefaultAsync(p => p.Id == id);
            if (plant == null) return NotFound();
            string basketStr = HttpContext.Request.Cookies["Basket"];

            BasketVM basket;

            if (string.IsNullOrEmpty(basketStr))
            {
                basket = new BasketVM();
                BasketCookieItemVM cookieItem = new BasketCookieItemVM
                {
                    Id = plant.Id,
                    Quantity = 1
                };
                basket.BasketCookieItemVMs = new List<BasketCookieItemVM>();
                basket.BasketCookieItemVMs.Add(cookieItem);
                basket.TotalPrice = plant.Price;

            }
            else
            {
                basket = JsonConvert.DeserializeObject<BasketVM>(basketStr);
                BasketCookieItemVM existed = basket.BasketCookieItemVMs.Find(p => p.Id == id);
                if(existed == null)
                {
                    BasketCookieItemVM cookieItem = new BasketCookieItemVM
                    {
                        Id = plant.Id,
                        Quantity = 1
                    };
                    basket.BasketCookieItemVMs.Add(cookieItem);
                    basket.TotalPrice += plant.Price;
                }
                else
                {
                    basket.TotalPrice += plant.Price;
                    existed.Quantity++;
                }
            }
            basketStr = JsonConvert.SerializeObject(basket);

            HttpContext.Response.Cookies.Append("Basket", basketStr);

            return RedirectToAction("Index","Home");
        }

        public IActionResult ShowBasket()
        {
            if (HttpContext.Request.Cookies["Basket"] == null) return NotFound();
            BasketVM basket = JsonConvert.DeserializeObject<BasketVM>(HttpContext.Request.Cookies["Basket"]);
            return Json(basket);
        }
    }
}

P127_Pronia/P127_Pronia/Views/Shared/_PlantsPartialView.cshtml
@foreach (Plant plant in Model)
                   {
                       <div class="col-xl-3 col-md-4 col-sm-6">
                      <div class="product-item">
                        <div class="product-img">
                          <a href="shop.html">
                            <img
                              class="primary-img"
                              src="~/assets/images/website-images//@plant.PlantImages.FirstOrDefault(x=>x.IsMain==true).Name"
                              alt="@plant.PlantImages.FirstOrDefault(x=>x.IsMain==true).Alternative"
                            />
                            <img
                              class="secondary-img"
                              src="~/assets/images/website-images//@plant.PlantImages.FirstOrDefault(x=>x.IsMain==null)?.Name"
                              alt="@plant.PlantImages.FirstOrDefault(x=>x.IsMain==null)?.Alternative"
                            />
                          </a>
                          <div class="product-add-action">
                            <ul>
                              <li>
                                <a
                                  href="wishlist.html"
                                  data-tippy="Add to wishlist"
                                  data-tippy-inertia="true"
                                  data-tippy-animation="shift-away"
                                  data-tippy-delay="50"
                                  data-tippy-arrow="true"
                                  data-tippy-theme="sharpborder"
                                >
                                  <i class="pe-7s-like"></i>
                                </a>
                              </li>
                              <li
                                class="quuickview-btn"
                                data-bs-toggle="modal"
                                data-bs-target="#quickModal"
                              >
                                <a
                                  asp-controller="plant"
                                   asp-action="getdetail"
                                   asp-route-id="@plant.Id"
                                  data-tippy="Quickview"
                                  data-tippy-inertia="true"
                                  data-tippy-animation="shift-away"
                                  data-tippy-delay="50"
                                  data-tippy-arrow="true"
                                  data-tippy-theme="sharpborder"
                                >
                                  <i class="pe-7s-look"></i>
                                </a>
                              </li>
                              <li>
                                <a
                                  asp-controller="Plant" asp-action="AddBasket" asp-route-id="@plant.Id"
                                  data-tippy="Add to cart"
                                  data-tippy-inertia="true"
                                  data-tippy-animation="shift-away"
                                  data-tippy-delay="50"
                                  data-tippy-arrow="true"
                                  data-tippy-theme="sharpborder"
                                >
                                  <i class="pe-7s-cart"></i>
                                </a>
                              </li>
                            </ul>
                          </div>
                        </div>
                        <div class="product-content">
                          <a class="product-name" href="shop.html"
                            >@plant.Name</a
                          >
                          <div class="price-box pb-1">
                            <span class="new-price">$@plant.Price</span>
                          </div>
                          <div class="rating-box">
                            <ul>
                              <li><i class="fa fa-star"></i></li>
                              <li><i class="fa fa-star"></i></li>
                              <li><i class="fa fa-star"></i></li>
                              <li><i class="fa fa-star"></i></li>
                              <li><i class="fa fa-star"></i></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    </div>
                   }

P127_Pronia/P127_Pronia/Views/Shared/_detailplant.cshtml
@model Plant
<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button"
                    class="btn-close"
                    data-bs-dismiss="modal"
                    aria-label="Close"
                    data-tippy="Close"
                    data-tippy-inertia="true"
                    data-tippy-animation="shift-away"
                    data-tippy-delay="50"
                    data-tippy-arrow="true"
                    data-tippy-theme="sharpborder"></button>
        </div>
        <div class="modal-body">
            <div class="modal-wrap row">
                <div class="col-lg-6">
                    <div class="modal-img">
                        <div class="swiper-container modal-slider">
                            <div class="swiper-wrapper">
                                <div class="swiper-slide">
                                    <a href="#" class="single-img">
                                        <img class="img-full"
                                             src="~/assets/images/product/large-size/@Model.PlantImages.FirstOrDefault(x=>x.IsMain==true).Name"
                                             alt="Product Image" />
                                    </a>
                                </div>
                                <div class="swiper-slide">
                                    <a href="#" class="single-img">
                                        <img class="img-full"
                                             src="~/assets/images/product/large-size/1-2-570x633.jpg"
                                             alt="Product Image" />
                                    </a>
                                </div>
                                <div class="swiper-slide">
                                    <a href="#" class="single-img">
                                        <img class="img-full"
                                             src="~/assets/images/product/large-size/1-3-570x633.jpg"
                                             alt="Product Image" />
                                    </a>
                                </div>
                                <div class="swiper-slide">
                                    <a href="#" class="single-img">
                                        <img class="img-full"
                                             src="~/assets/images/product/large-size/1-4-570x633.jpg"
                                             alt="Product Image" />
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 pt-5 pt-lg-0">
                    <div class="single-product-content">
                        <h2 class="title">@Model.Name</h2>
                        <div class="price-box">
                            <span class="new-price">$@Model.Price</span>
                        </div>
                        <div class="rating-box-wrap">
                            <div class="rating-box">
                                <ul>
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                    <li><i class="fa fa-star"></i></li>
                                </ul>
                            </div>
                            <div class="review-status">
                                <a href="#">( 1 Review )</a>
                            </div>
                        </div>
                        <div class="selector-wrap color-option">
                            <span class="selector-title border-bottom-0">Color</span>
                            <select class="nice-select wide border-bottom-0 rounded-0">
                                <option value="default">Black & White</option>
                                <option value="blue">Blue</option>
                                <option value="green">Green</option>
                                <option value="red">Red</option>
                            </select>
                        </div>
                        <div class="selector-wrap size-option">
                            <span class="selector-title">Size</span>
                            <select class="nice-select wide rounded-0">
                                <option value="medium">Medium Size & Poot</option>
                                <option value="large">Large Size With Poot</option>
                                <option value="small">Small Size With Poot</option>
                            </select>
                        </div>
                        <p class="short-desc">
                            Lorem ipsum dolor sit amet, consectetur adipisic elit, sed
                            do eiusmod tempo incid ut labore et dolore magna aliqua.
                            Ut enim ad minim veniam, quis nostru exercitation ullamco
                            laboris nisi ut aliquip ex ea commodo consequat. Duis aute
                            irure dolor in reprehenderit in voluptate
                        </p>
                        <ul class="quantity-with-btn">
                            <li class="quantity">
                                <div class="cart-plus-minus">
                                    <input class="cart-plus-minus-box"
                                           value="1"
                                           type="text" />
                                </div>
                            </li>
                            <li class="add-to-cart">
                                <a class="btn btn-custom-size lg-size btn-pronia-primary"
                                   href="cart.html">Add to cart</a>
                            </li>
                            <li class="wishlist-btn-wrap">
                                <a class="custom-circle-btn" href="wishlist.html">
                                    <i class="pe-7s-like"></i>
                                </a>
                            </li>
                            <li class="compare-btn-wrap">
                                <a class="custom-circle-btn" href="compare.html">
                                    <i class="pe-7s-refresh-2"></i>
                                </a>
                            </li>
                        </ul>
                        <ul class="service-item-wrap pb-0">
                            <li class="service-item">
                                <div class="service-img">
                                    <img src="~/assets/images/shipping/icon/car.png"
                                         alt="Shipping Icon" />
                                </div>
                                <div class="service-content">
                                    <span class="title">
                                        Free <br />
                                        Shipping
                                    </span>
                                </div>
                            </li>
                            <li class="service-item">
                                <div class="service-img">
                                    <img src="~/assets/images/shipping/icon/card.png"
                                         alt="Shipping Icon" />
                                </div>
                                <div class="service-content">
                                    <span class="title">
                                        Safe <br />
                                        Payment
                                    </span>
                                </div>
                            </li>
                            <li class="service-item">
                                <div class="service-img">
                                    <img src="~/assets/images/shipping/icon/service.png"
                                         alt="Shipping Icon" />
                                </div>
                                <div class="service-content">
                                    <span class="title">
                                        Safe <br />
                                        Payment
                                    </span>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>